"""initial schema - 37 tables (26 business + 11 operational entities, BP-0006/BP-0007)

Revision ID: f8d91060004d
Revises: 
Create Date: 2026-07-17 19:21:27.358241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8d91060004d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agentes',
    sa.Column('rol', sa.String(length=100), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('responsible', sa.String(length=255), nullable=True),
    sa.Column('evidence_source', sa.String(length=500), nullable=True),
    sa.Column('confidence_level', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('empresas',
    sa.Column('razon_social', sa.String(length=255), nullable=False),
    sa.Column('jurisdiccion', sa.String(length=100), nullable=True),
    sa.Column('tipo_societario', sa.String(length=100), nullable=True),
    sa.Column('madurez_organizacional', sa.Float(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('responsible', sa.String(length=255), nullable=True),
    sa.Column('evidence_source', sa.String(length=500), nullable=True),
    sa.Column('confidence_level', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mercados',
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('tamano', sa.String(length=100), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('responsible', sa.String(length=255), nullable=True),
    sa.Column('evidence_source', sa.String(length=500), nullable=True),
    sa.Column('confidence_level', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles_funcionales',
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('descripcion', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('responsible', sa.String(length=255), nullable=True),
    sa.Column('evidence_source', sa.String(length=500), nullable=True),
    sa.Column('confidence_level', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('responsible', sa.String(length=255), nullable=True),
    sa.Column('evidence_source', sa.String(length=500), nullable=True),
    sa.Column('confidence_level', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_table('accionistas_inversionistas',
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('tipo_participacion', sa.String(length=100), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('responsible', sa.String(length=255), nullable=True),
    sa.Column('evidence_source', sa.String(length=500), nullable=True),
    sa.Column('confidence_level', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('activos',
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.String(length=100), nullable=True),
    sa.Column('valor', sa.Float(), nullable=True),
    sa.Column('liquidez', sa.String(length=50), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('responsible', sa.String(length=255), nullable=True),
    sa.Column('evidence_source', sa.String(length=500), nullable=True),
    sa.Column('confidence_level', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clientes_finales',
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('segmento', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('responsible', sa.String(length=255), nullable=True),
    sa.Column('evidence_source', sa.String(length=500), nullable=True),
    sa.Column('confidence_level', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('competidores',
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('mercado_id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('responsible', sa.String(length=255), nullable=True),
    sa.Column('evidence_source', sa.String(length=500), nullable=True),
    sa.Column('confidence_level', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['mercado_id'], ['mercados.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contratos_negocio',
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('parte', sa.String(length=255), nullable=True),
    sa.Column('vigencia', sa.String(length=100), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('responsible', sa.String(length=255), nullable=True),
    sa.Column('evidence_source', sa.String(length=500), nullable=True),
    sa.Column('confidence_level', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('decisiones_negocio',
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('descripcion', sa.String(), nullable=False),
    sa.Column('opcion_elegida', sa.String(), nullable=True),
    sa.Column('opcion_recomendada', sa.String(), nullable=True),
    sa.Column('nivel_evidencia', sa.String(length=50), nullable=True),
    sa.Column('riesgos_asumidos', sa.String(), nullable=True),
    sa.Column('responsabilidad_asumida', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('responsible', sa.String(length=255), nullable=True),
    sa.Column('evidence_source', sa.String(length=500), nullable=True),
    sa.Column('confidence_level', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('departamentos',
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('departamento_padre_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('responsible', sa.String(length=255), nullable=True),
    sa.Column('evidence_source', sa.String(length=500), nullable=True),
    sa.Column('confidence_level', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['departamento_padre_id'], ['departamentos.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documentos',
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('origen', sa.String(length=50), nullable=False),
    sa.Column('url_o_contenido', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('responsible', sa.String(length=255), nullable=True),
    sa.Column('evidence_source', sa.String(length=500), nullable=True),
    sa.Column('confidence_level', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gastos',
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('categoria', sa.String(length=100), nullable=True),
    sa.Column('monto', sa.Float(), nullable=True),
    sa.Column('periodicidad', sa.String(length=50), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('responsible', sa.String(length=255), nullable=True),
    sa.Column('evidence_source', sa.String(length=500), nullable=True),
    sa.Column('confidence_level', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ingresos',
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('fuente', sa.String(length=255), nullable=True),
    sa.Column('monto', sa.Float(), nullable=True),
    sa.Column('periodicidad', sa.String(length=50), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('responsible', sa.String(length=255), nullable=True),
    sa.Column('evidence_source', sa.String(length=500), nullable=True),
    sa.Column('confidence_level', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('iniciativas',
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('objetivo', sa.String(), nullable=True),
    sa.Column('presupuesto', sa.Float(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('responsible', sa.String(length=255), nullable=True),
    sa.Column('evidence_source', sa.String(length=500), nullable=True),
    sa.Column('confidence_level', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('marcas',
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('posicionamiento', sa.String(), nullable=True),
    sa.Column('es_intangible', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('responsible', sa.String(length=255), nullable=True),
    sa.Column('evidence_source', sa.String(length=500), nullable=True),
    sa.Column('confidence_level', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('narrativas_fundacionales',
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('relato_origen', sa.String(), nullable=True),
    sa.Column('motivacion_fundadora', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('responsible', sa.String(length=255), nullable=True),
    sa.Column('evidence_source', sa.String(length=500), nullable=True),
    sa.Column('confidence_level', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id')
    )
    op.create_table('objetivos',
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('declaracion', sa.String(), nullable=False),
    sa.Column('horizonte_tiempo', sa.String(length=50), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('responsible', sa.String(length=255), nullable=True),
    sa.Column('evidence_source', sa.String(length=500), nullable=True),
    sa.Column('confidence_level', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pasivos',
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.String(length=100), nullable=True),
    sa.Column('monto', sa.Float(), nullable=True),
    sa.Column('plazo', sa.String(length=50), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('responsible', sa.String(length=255), nullable=True),
    sa.Column('evidence_source', sa.String(length=500), nullable=True),
    sa.Column('confidence_level', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('procesos',
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('objetivo_proceso', sa.String(), nullable=True),
    sa.Column('frecuencia', sa.String(length=100), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('responsible', sa.String(length=255), nullable=True),
    sa.Column('evidence_source', sa.String(length=500), nullable=True),
    sa.Column('confidence_level', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('productos_servicios',
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('categoria', sa.String(length=255), nullable=True),
    sa.Column('propuesta_valor', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('responsible', sa.String(length=255), nullable=True),
    sa.Column('evidence_source', sa.String(length=500), nullable=True),
    sa.Column('confidence_level', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('proveedores',
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('criticidad', sa.String(length=50), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('responsible', sa.String(length=255), nullable=True),
    sa.Column('evidence_source', sa.String(length=500), nullable=True),
    sa.Column('confidence_level', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('proyectos',
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('usuario_principal_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('responsible', sa.String(length=255), nullable=True),
    sa.Column('evidence_source', sa.String(length=500), nullable=True),
    sa.Column('confidence_level', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['usuario_principal_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id')
    )
    op.create_table('scores',
    sa.Column('empresa_id', sa.UUID(), nullable=True),
    sa.Column('usuario_id', sa.UUID(), nullable=True),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('responsible', sa.String(length=255), nullable=True),
    sa.Column('evidence_source', sa.String(length=500), nullable=True),
    sa.Column('confidence_level', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sucesos_empresariales',
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('naturaleza', sa.String(length=50), nullable=True),
    sa.Column('descripcion', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('responsible', sa.String(length=255), nullable=True),
    sa.Column('evidence_source', sa.String(length=500), nullable=True),
    sa.Column('confidence_level', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cargos',
    sa.Column('departamento_id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('nivel_jerarquico', sa.Integer(), nullable=True),
    sa.Column('reporta_a_cargo_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('responsible', sa.String(length=255), nullable=True),
    sa.Column('evidence_source', sa.String(length=500), nullable=True),
    sa.Column('confidence_level', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['departamento_id'], ['departamentos.id'], ),
    sa.ForeignKeyConstraint(['reporta_a_cargo_id'], ['cargos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('decisiones_adan',
    sa.Column('proyecto_id', sa.UUID(), nullable=False),
    sa.Column('decision_negocio_id', sa.UUID(), nullable=True),
    sa.Column('descripcion', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('responsible', sa.String(length=255), nullable=True),
    sa.Column('evidence_source', sa.String(length=500), nullable=True),
    sa.Column('confidence_level', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['decision_negocio_id'], ['decisiones_negocio.id'], ),
    sa.ForeignKeyConstraint(['proyecto_id'], ['proyectos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('eventos',
    sa.Column('proyecto_id', sa.UUID(), nullable=False),
    sa.Column('suceso_empresarial_id', sa.UUID(), nullable=True),
    sa.Column('tipo', sa.String(length=100), nullable=False),
    sa.Column('payload', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('responsible', sa.String(length=255), nullable=True),
    sa.Column('evidence_source', sa.String(length=500), nullable=True),
    sa.Column('confidence_level', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['proyecto_id'], ['proyectos.id'], ),
    sa.ForeignKeyConstraint(['suceso_empresarial_id'], ['sucesos_empresariales.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('metas',
    sa.Column('objetivo_id', sa.UUID(), nullable=False),
    sa.Column('valor_objetivo', sa.String(length=100), nullable=True),
    sa.Column('fecha_limite', sa.String(length=20), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('responsible', sa.String(length=255), nullable=True),
    sa.Column('evidence_source', sa.String(length=500), nullable=True),
    sa.Column('confidence_level', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['objetivo_id'], ['objetivos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('niveles',
    sa.Column('proyecto_id', sa.UUID(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('completado', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('responsible', sa.String(length=255), nullable=True),
    sa.Column('evidence_source', sa.String(length=500), nullable=True),
    sa.Column('confidence_level', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['proyecto_id'], ['proyectos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios_proyectos',
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('proyecto_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['proyecto_id'], ['proyectos.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('usuario_id', 'proyecto_id')
    )
    op.create_table('workspaces',
    sa.Column('proyecto_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('responsible', sa.String(length=255), nullable=True),
    sa.Column('evidence_source', sa.String(length=500), nullable=True),
    sa.Column('confidence_level', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['proyecto_id'], ['proyectos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('proyecto_id')
    )
    op.create_table('cards',
    sa.Column('nivel_id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('responsible', sa.String(length=255), nullable=True),
    sa.Column('evidence_source', sa.String(length=500), nullable=True),
    sa.Column('confidence_level', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['nivel_id'], ['niveles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('empleados',
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('cargo_id', sa.UUID(), nullable=True),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('fecha_ingreso', sa.String(length=20), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('responsible', sa.String(length=255), nullable=True),
    sa.Column('evidence_source', sa.String(length=500), nullable=True),
    sa.Column('confidence_level', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['cargo_id'], ['cargos.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('indicadores',
    sa.Column('meta_id', sa.UUID(), nullable=False),
    sa.Column('formula_conceptual', sa.String(), nullable=True),
    sa.Column('frecuencia_medicion', sa.String(length=50), nullable=True),
    sa.Column('valor_actual', sa.Float(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('responsible', sa.String(length=255), nullable=True),
    sa.Column('evidence_source', sa.String(length=500), nullable=True),
    sa.Column('confidence_level', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['meta_id'], ['metas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conversaciones',
    sa.Column('card_id', sa.UUID(), nullable=False),
    sa.Column('canal', sa.String(length=50), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('responsible', sa.String(length=255), nullable=True),
    sa.Column('evidence_source', sa.String(length=500), nullable=True),
    sa.Column('confidence_level', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tareas',
    sa.Column('nivel_id', sa.UUID(), nullable=True),
    sa.Column('card_id', sa.UUID(), nullable=True),
    sa.Column('descripcion', sa.String(), nullable=False),
    sa.Column('completada', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('responsible', sa.String(length=255), nullable=True),
    sa.Column('evidence_source', sa.String(length=500), nullable=True),
    sa.Column('confidence_level', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ),
    sa.ForeignKeyConstraint(['nivel_id'], ['niveles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agentes_conversaciones',
    sa.Column('agente_id', sa.UUID(), nullable=False),
    sa.Column('conversacion_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['agente_id'], ['agentes.id'], ),
    sa.ForeignKeyConstraint(['conversacion_id'], ['conversaciones.id'], ),
    sa.PrimaryKeyConstraint('agente_id', 'conversacion_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('agentes_conversaciones')
    op.drop_table('tareas')
    op.drop_table('conversaciones')
    op.drop_table('indicadores')
    op.drop_table('empleados')
    op.drop_table('cards')
    op.drop_table('workspaces')
    op.drop_table('usuarios_proyectos')
    op.drop_table('niveles')
    op.drop_table('metas')
    op.drop_table('eventos')
    op.drop_table('decisiones_adan')
    op.drop_table('cargos')
    op.drop_table('sucesos_empresariales')
    op.drop_table('scores')
    op.drop_table('proyectos')
    op.drop_table('proveedores')
    op.drop_table('productos_servicios')
    op.drop_table('procesos')
    op.drop_table('pasivos')
    op.drop_table('objetivos')
    op.drop_table('narrativas_fundacionales')
    op.drop_table('marcas')
    op.drop_table('iniciativas')
    op.drop_table('ingresos')
    op.drop_table('gastos')
    op.drop_table('documentos')
    op.drop_table('departamentos')
    op.drop_table('decisiones_negocio')
    op.drop_table('contratos_negocio')
    op.drop_table('competidores')
    op.drop_table('clientes_finales')
    op.drop_table('activos')
    op.drop_table('accionistas_inversionistas')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_table('roles_funcionales')
    op.drop_table('mercados')
    op.drop_table('empresas')
    op.drop_table('agentes')
    # ### end Alembic commands ###
